local_backend: true
backend:
  name: git-gateway
  branch: master
logo_url: https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png
locale: 'es'
media_folder: "static/images" # Folder where user uploaded files should go
public_folder: "images"
collections:
  - name: "settings"
    label: "Ajustes"
    editor:
      preview: false
    files:
      - file: "data/settings.yml"
        label: "General"
        name: "general"
        fields:
          - {label: "Título del sitio", name: "title", widget: "string"}
          - {label: "Logo", name: "logo", widget: "image"}
          - {label: "Favicon", name: "favicon", widget: "image"}
          - {label: "Teléfono", name: "phone", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Dirección", name: "address", widget: "string"}
      - file: "data/colors.yml"
        label: "Colores"
        name: "colors"
        fields:
          - {label: "Color principal", name: "main_color", widget: "color"}
          - {label: "Color secundario", name: "second_color", widget: "color"}
          - {label: "Color de textos", name: "body_color", widget: "color"}
  - name: "posts" # Used in routes, e.g., /admin/collections/post
    label: "Posts" # Used in the UI
    folder: "content/posts" # The path to the folder where the documents are stored
    path: "{{slug}}/index"
    media_folder: "" # Save images in the post's own folder instead of the static folder
    public_folder: ""
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Featured Image"
        name: "featured_image"
        widget: "object"
        fields:
          - {name: src, label: Image, widget: image}
          - {name: alt, label: Alt text, widget: string}
          - {name: title, label: Title, widget: string}
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Blurb", name: "blurb", widget: "text" }
          - {
              label: "Ajustes SEO",
              name: "seo",
              widget: "object",
              fields:
                [
                  { label: "Título", name: "title_seo", widget: "string", required: false },
                  { label: "Descripción", name: "description_seo", widget: "text", required: false },
                ],
            }
      - file: "content/about/index.md"
        label: "About"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "text" }
